### ISSUE TITLE
[ContributionCounter] Sync players' contribution with the host

### ISSUE THREAD

**Issue by rclim95** [rclim95/StardewValleyMods#4]
Players who have joined a farm hosted by another player will need to sync their contributions to the host so the host knows who has been contributing what.

This will require the mod to do the following:
~~1. Detect if the current player is hosting a service.~~
~~2. If the player is hosting the server, keep track of other people's contributions (for record keeping) in addition to the contributions that the host player has made.~~
~~3. If the player is a guest of the server (i.e., not hosting), communicate to the host the contributions that the player has made so far.~~
~~4. At the end of a game day, collect everyone's contributions and store the information in the database for record keeping.~~

First question: how does one broadcast messages to one another? 🤔

**Comment by rclim95** [comment]
For sending and receiving messages, we might want to check out PyTK, which provides a standardized API for sending and receiving messages through Stardew Valley's network connection. [Some examples are here](https://github.com/Platonymous/Stardew-Valley-Mods/blob/master/PyTK/Examples.md#multiplayer).

**Comment by Tready07** [comment]
We were able to use PyTK to broadcast messages. Consider an ideal time for providing the update (end of the day event ?) **NOTE:** @rclim95 *solved a serializable issue by making the Contribution Class serialiable and marked the elements as XMLelements (which was required by the PYTK)*
