### ISSUE TITLE
Store contributions database inside the mod folder

### ISSUE THREAD

**Issue by rclim95** [rclim95/StardewValleyMods#6]
Currently, the `Contributions.db` database file is being stored in the current directory of SMAPI/Stardew Valley, which appears to be the folder where Stardew Valley is installed on the player's PC. This is due to the fact that we specify a relative path to the database whenever we're making a connection to the database. (See [`ModEntry.cs:48`](https://github.com/rclim95/StardewValleyMods/blob/master/ContributionCounter/ModEntry.cs#L48) for an example of this).

What the mod should be doing is using an absolute path to the `Contributions.db` file such that the database file is created/referenced inside the mod's personal folder. That way, the mod isn't susceptible to misplacing the `Contributions.db` file somewhere else (especially with it using a relative path, which is subject to change depending on what the current directory of Stardew Valley/SMAPI is), and we don't happen to pollute the Stardew Valley folder with data that's specific to the Contributions Counter mod.

**Comment by rclim95** [comment]
## Tiny Tidbits

`IModHelper.DirectoryPath` returns a string to the full path of where the mod is installed. This is probably what we should based our `Contributions.db` absolute path on, so that the database is created inside that folder.

**Comment by Tready07** [comment]
Which branch do you want this to be done to? @rclim95

**Comment by rclim95** [comment]
LGTM! 😄 

One small change though--I used [`Path.Combine`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=netframework-4.7.1#System_IO_Path_Combine_System_String___) to build the database path. That should resolve the whole back slash/forward slash issue when SMAPI/Stardew Valley is running on Windows vs. Linux.
